# Preface {.unnumbered}

## Description

This course will cover the topics in the theory and practice of *Bayesian statistical inference*, ranging from a review of fundamentals to questions of current research interest. Motivation for the Bayesian approach. Bayesian computation, Monte Carlo methods, asymptotics. Model checking and comparison. A selection of examples and issues in modelling and data analysis. Discussion of advantages and difficulties of the Bayesian approach. This course will be computationally intensive through analysis of data sets using the R statistical computing language.

### Prerequisites

MATH 4752/6752 -- Mathematical Statistics II or equivalent, and the ability to program in a high-level language.

### Instructor

[Chi-Kuang Yeh](https://chikuang.github.io/), Assistant Professor in the [Department of Mathematics and Statistics](https://mathstat.gsu.edu/), [Georgia State University](https://www.gsu.edu/).

-   Office: Suite 1407, 25 Park Place.
-   Email: [cyeh\@gsu.edu](mailto:cyeh@gsu.edu).

## Office Hour

10:00--13:00 on Monday, or by appointment.

## Grade Distribution

-   Homework -- 50%
-   Exam -- 30%
-   Final -- 20%

## Assignment

-   [x] A1, due on Jan 29, 2026
-   [x] A2, due on Feb 13, 2026
-   [x] A3, due on Mar 01, 2026
-   [x] A4, due on Mar 25, 2026
-   [ ] A5, due on Apr 20, 2026

## Midterm

-   [x] March 5, 2026

## Topics and Corresponding Lectures

Those chapters are based on the lecture notes. This part will be updated frequently.

| Status | Chapter |              Topic              |    Lecture    |
|:------:|:-------:|:-------------------------------:|:-------------:|
|   ✅   |  Ch. 1  |      Welcome and Overview       |       1       |
|   ✅   |    —    |     Intro to R Programming      |       2       |
|   ✅   |  Ch. 2  | Probability and Exchangeability |     3--5      |
|   ✅   |  Ch. 3  |      One Parameter Models       |     6--9      |
|   ✅   |  Ch. 4  |           Monte Carlo           |    10-- 13    |
|  ✅ ️   |  Ch.5   |          Gibbs Sampler          | 14,17--18, 20 |
|   ✅   |         |         Midterm Review          |      15       |
|   ✅   |         |          Midterm Exam           |      16       |
|        |         |        ⛱ Spring Break 🌊        |               |
|   ✅   |   \-    |     Intro to JAGS and BUGS      |      19       |
|   ✅   |  Ch.6   |         MCMC Diagnosis          |     20-22     |
|   ✅  |  Ch.7  |         Multivariate Gaussian          |     22-- 26  |
|  ️️⏳  | Ch. 8  |Bayesian in Machine Learning: Regularization, Prediction, and Uncertainty    |                    27|
|  ️️⏳  | Ch. 9 |Modern Bayesian Computation and Models: Variational Inference and Gaussian Processes |                    28|
 
<!-- 🚧🛠️⏳   -->

## Recommended Textbooks

-   Gelman, A., Carlin, J., Stern, H., Rubin, D., Dunson, D., and Vehtari, A. (2021). [Bayesian Data Analysis](https://sites.stat.columbia.edu/gelman/book/), CRC Press, 3rd Ed.

-   Hoff, P.D. (2009). [A First Course in Bayesian Statistical Methods](https://sites.math.rutgers.edu/~zeilberg/EM20/Hoff.pdf), Springer.

-   McElreath, R. (2018). [Statistical Rethinking: A Bayesian Course with Examples in R and Stan](https://civil.colorado.edu/~balajir/CVEN6833/bayes-resources/RM-StatRethink-Bayes.pdf), CRC Press.

## Side Readings

-   Just Another Gibbs Sampler [Page](https://mcmc-jags.sourceforge.io/)
-   BUGS and Winbugs from MRC Biostatistics unit [Page](https://www.mrc-bsu.cam.ac.uk/software/bugs-project)
